"""Crear tabla empleados

Revision ID: 4e3809733857
Revises: 
Create Date: 2026-06-02 04:05:47.293788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e3809733857'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('empleados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.Column('contraseña', sa.String(length=100), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_empleados_dni'), 'empleados', ['dni'], unique=True)
    op.create_index(op.f('ix_empleados_id'), 'empleados', ['id'], unique=False)
    op.create_index(op.f('ix_empleados_usuario'), 'empleados', ['usuario'], unique=True)
    op.create_table('medicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=50), nullable=True),
    sa.Column('especialidad', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tecnicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('area_experiencia', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legajo', sa.String(length=50), nullable=True),
    sa.Column('comisiones', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendedores')
    op.drop_table('tecnicos')
    op.drop_table('medicos')
    op.drop_index(op.f('ix_empleados_usuario'), table_name='empleados')
    op.drop_index(op.f('ix_empleados_id'), table_name='empleados')
    op.drop_index(op.f('ix_empleados_dni'), table_name='empleados')
    op.drop_table('empleados')
    # ### end Alembic commands ###
