"""nueva_arquitectura_personas

Revision ID: 7f63bc5e6525
Revises: 
Create Date: 2026-06-04 00:04:45.382016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f63bc5e6525'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellido', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('tipo_persona', sa.String(length=50), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personas_dni'), 'personas', ['dni'], unique=True)
    op.create_index(op.f('ix_personas_id'), 'personas', ['id'], unique=False)
    op.create_table('empleados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legajo', sa.String(length=50), nullable=False),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.Column('contraseña', sa.String(length=100), nullable=False),
    sa.Column('rol', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legajo')
    )
    op.create_index(op.f('ix_empleados_usuario'), 'empleados', ['usuario'], unique=True)
    op.create_table('pacientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('obra_social', sa.String(length=100), nullable=True),
    sa.Column('historial_medico', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['personas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula', sa.String(length=50), nullable=False),
    sa.Column('especialidad', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tecnicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matricula_optico', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendedores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comisiones', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['empleados.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendedores')
    op.drop_table('tecnicos')
    op.drop_table('medicos')
    op.drop_table('pacientes')
    op.drop_index(op.f('ix_empleados_usuario'), table_name='empleados')
    op.drop_table('empleados')
    op.drop_index(op.f('ix_personas_id'), table_name='personas')
    op.drop_index(op.f('ix_personas_dni'), table_name='personas')
    op.drop_table('personas')
    # ### end Alembic commands ###
